# -*- coding: utf-8 -*-
"""ques4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PInEbI7E2yRpsocn7uBgwSjRrzM4KJCt
"""

#4. IndexError Handler

try:
  my_list = [1, 2, 3]
  print(my_list[3])
except IndexError:
  print("Error: Index out of range")